plugins { id 'com.android.application' }

android {
    namespace 'com.abusobhi.pdfvoicereader'
    compileSdk 36

    defaultConfig {
        applicationId 'com.abusobhi.pdfvoicereader'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
